server:
  port: 9191
  
  
spring:
  application:
     name: API-GATEWAY
       
     cloud:
      gateway:
       routes:
        - id: CATOGORIES-SERVICE
          uri: lb://CATOGORIES-SERVICE
          predicates:
            - Path=/catogory/save/**
            - Path=/catogory/{catogoryId}/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8763/eureka/
  instance:
    hostname: localhost

  