server:
  port: 9003

spring:
  application:
    name: Order-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8763/eureka/
  instance:
    hostname: localhost
