server:
  port:  9091

spring:
  application:
    name: CATOGORIES-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8763/eureka/
  instance:
    hostname: localhost